from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router for the DRF viewsets
router = DefaultRouter()
router.register(r'lessons', views.LessonViewSet)
router.register(r'progress', views.LessonProgressViewSet)

urlpatterns = [
    # List all lessons
    path('', views.lesson_list, name='lesson_list'),
    
    # Detail view for a lesson with primary key as integer
    path('<int:pk>/', views.lesson_detail, name='lesson_detail'),
    
    # Download lesson content as text file
    path('<int:pk>/download/', views.lesson_download, name='lesson_download'),
    
    # Include API routes generated by DRF router
    path('api/', include(router.urls)),
]
