from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a DefaultRouter instance for DRF viewsets
router = DefaultRouter()
# Register the CustomUserViewSet with the router under the 'users' prefix
router.register(r'users', views.CustomUserViewSet)

urlpatterns = [
    # URL pattern for user login page/view
    path('login/', views.login_view, name='login'),
    # URL pattern for user registration page/view
    path('register/', views.register_view, name='register'),
    # URL pattern for user profile page/view (requires login)
    path('profile/', views.profile_view, name='profile'),
    # URL pattern for user settings page/view (requires login)
    path('settings/', views.settings_view, name='settings'),
    # Include the API routes generated by the DRF router (e.g., /api/users/)
    path('api/', include(router.urls)),
]
